// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Must stay in sync with backend/lib/db.ts, which reads backend/dev.db.
    url: process.env["DATABASE_URL"] || "file:./backend/dev.db",
  },
});
